# itk-version: 3.2.1
networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    networks:
      - app
      - frontend
    depends_on:
      - app
      - shipment_worker
      - registration_worker
      - office
    ports:
      - '8080'
    volumes:
      - ./.docker/templates:/etc/nginx/templates:ro
    environment:
      NGINX_WEB_ROOT: /app
      NGINX_PORT: 8080
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"
#      HTTPS config - uncomment to enable redirect from :80 to :443
#      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    command: "python src/OpenPostbud/main.py"
    networks:
      - app
    volumes:
      - ./:/app
      - ./certs:/app/certs:ro

  shipment_worker:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    command: "python src/OpenPostbud/workers/shipment_worker.py"
    depends_on:
      - app
      - office
    networks:
      - app
    volumes:
      - ./:/app
      - ./certs:/app/certs:ro

  registration_worker:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    command: "python src/OpenPostbud/workers/registration_worker.py"
    depends_on:
      - app
    networks:
      - app
    volumes:
      - ./:/app
      - ./certs:/app/certs:ro

  office:
    build:
      context: .
      dockerfile: .docker/office/Dockerfile
    command: "python src/OpenPostbud/workers/pdf_converter.py"
    networks:
      - app
