# itk-version: 3.2.1
networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    networks:
      - app
      - frontend
    depends_on:
      - app
    ports:
      - '8080'
    volumes:
      - ./.docker/templates:/etc/nginx/templates:ro
      - ./ui:/app
    env_file:
      - path: .env
        required: true
      - path: .env.docker.local
        required: false
    environment:
      NGINX_WEB_ROOT: /app
      NGINX_PORT: 8080
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"
#      HTTPS config - uncomment to enable redirect from :80 to :443
#      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    command: "python src/OpenPostbud/main.py"
    networks:
      - app
    ports:
      - "8080"
    environment:
      - CONTAINER_EMBEDDING_MODEL_PATH=/model
    volumes:
      - ./:/app
