ALTER TABLE "Shipments" ADD COLUMN owner_group VARCHAR NOT NULL DEFAULT ''


ALTER TABLE "NemSMS_Shipments" ADD COLUMN owner_group VARCHAR NOT NULL DEFAULT ''


ALTER TABLE "RegistrationJobs" ADD COLUMN owner_group VARCHAR NOT NULL DEFAULT ''


ALTER TABLE "ApiUsers" ADD COLUMN owner_group VARCHAR NOT NULL DEFAULT ''
