"""This module contains the 'admin'login' page."""

from fastapi import HTTPException
from fastapi.responses import RedirectResponse
from nicegui import app, APIRouter

from OpenPostbud.middleware import authentication

router = APIRouter()

@router.page("/admin-login", name="Admin Login")
def admin_login(token: str) -> RedirectResponse:
    """This page is used to authenticate with an admin token.
    The token is generated by calling the 'admin_access' subcommand
    in the CLI.
    """

    if authentication.get_admin_token() == token:
        authentication.authenticate("ADMIN", roles=["Admin"])
        return RedirectResponse(app.url_path_for("Front Page"))

    raise HTTPException(401, "Invalid admin token")
