"""This module contains the 'admin'login' page."""

from fastapi import HTTPException
from fastapi.responses import RedirectResponse
from nicegui import ui

from OpenPostbud.middleware import authentication


@ui.page("/admin_login")
def admin_login(token: str) -> RedirectResponse:
    """This page is used to authenticate with an admin token.
    The token is generated by calling the 'admin_access' subcommand
    in the CLI.
    """

    if authentication.get_admin_token() == token:
        authentication.authenticate("ADMIN")
        return RedirectResponse("/")

    raise HTTPException(401, "Invalid admin token")
